//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlLesson12_Ontap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DTL_SACH
    {
        [Display(Name ="Mã sách")]
        public string Dtl_MaSach { get; set; }
        [Display(Name = "Tên sách")]
        public string Dtl_TenSach { get; set; }
        [Display(Name = "Số trang")]
        public Nullable<decimal> Dtl_SoTrang { get; set; }
        [Display(Name = "Năm xuất bản")]
        public Nullable<System.DateTime> Dtl_NamXB { get; set; }
        [Display(Name = "Mã tác giả")]
        public string Dtl_MaTG { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> Dtl_TrangThai { get; set; }
    
        public virtual DTL_TACGIA DTL_TACGIA { get; set; }
    }
}
