//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlLesson12_Ontap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DinhTienLuc_2210900038Entities : DbContext
    {
        public DinhTienLuc_2210900038Entities()
            : base("name=DinhTienLuc_2210900038Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DTL_SACH> DTL_SACH { get; set; }
        public virtual DbSet<DTL_TACGIA> DTL_TACGIA { get; set; }
    }
}
