//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlK22Cnt4Lesson10CB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtlAccount
    {
        public int DtlId { get; set; }
        public string DtlUserName { get; set; }
        public string DtlPassword { get; set; }
        public string DtlFullName { get; set; }
        public string DtlEmail { get; set; }
        public string DtlPhone { get; set; }
        public Nullable<bool> DtlActive { get; set; }
    }
}
