//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlK22CNT4Lesson07DF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DtlK22CNT4Lesson07DbEntities1 : DbContext
    {
        public DtlK22CNT4Lesson07DbEntities1()
            : base("name=DtlK22CNT4Lesson07DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtlKhoa> dtlKhoas { get; set; }
        public virtual DbSet<dtlSinhVien> dtlSinhViens { get; set; }
    }
}
