//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlK22CNT4Lesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class dtlKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtlKhoa()
        {
            this.dtlSinhViens = new HashSet<dtlSinhVien>();
        }
        [DisplayName("Mã khoa")]

        public string dtlMaKH { get; set; }
        [DisplayName("Mã tên khoa")]
        public string dtlTenKhoa { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> dtlTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtlSinhVien> dtlSinhViens { get; set; }
    }
}
