//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlK22CNT4Lesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class dtlSinhVien
    {
        public string dtkMaSV { get; set; }
        [DisplayName("Mã sinh viên")]
        public string DtlHoSV { get; set; }
        [DisplayName("Tên")]
        public string DtlTenSV { get; set; }
        [DisplayName("Giới tính")]
        public Nullable<bool> DtlPhai { get; set; }
        public string DtlEmail { get; set; }
        [DisplayName("Số điện thoại")]
        public string DtlPhone { get; set; }
        [DisplayName("Mã khoa")]
        public string DtlMaKH { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> DtlTrangThai { get; set; }
    
        public virtual dtlKhoa dtlKhoa { get; set; }
    }
}
