//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlLesson11_OnTap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DtlCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DtlCategory()
        {
            this.DtlProducts = new HashSet<DtlProduct>();
        }
        [Display(Name ="Mã danh mục")]
        
        public int DtlId { get; set; }
        [Display(Name = "Tên danh mục")]
        public string DtlCateName { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> DtlStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtlProduct> DtlProducts { get; set; }
    }
}
